apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T10:39:05Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7651"
  uid: e2a840ca-9a3d-46a6-95eb-888881b595ba
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.134.6
  clusterIPs:
  - 10.111.134.6
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30404
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
